# Generated by Django 4.2.7 on 2025-12-01 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True, verbose_name='센서 ID')),
                ('name', models.CharField(max_length=100, verbose_name='센서 이름')),
                ('sensor_type', models.CharField(choices=[('temperature', '온도'), ('humidity', '습도'), ('pressure', '압력'), ('gas', '가스')], max_length=20, verbose_name='센서 타입')),
                ('location', models.CharField(max_length=200, verbose_name='설치 위치')),
                ('status', models.CharField(choices=[('active', '정상'), ('warning', '경고'), ('error', '오류'), ('offline', '오프라인')], default='active', max_length=20, verbose_name='상태')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '센서',
                'verbose_name_plural': '센서 목록',
                'db_table': 'sensors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('critical', '심각')], max_length=20, verbose_name='심각도')),
                ('status', models.CharField(choices=[('active', '활성'), ('acknowledged', '확인됨'), ('resolved', '해결됨')], default='active', max_length=20, verbose_name='상태')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('threshold_value', models.FloatField(verbose_name='임계값')),
                ('actual_value', models.FloatField(verbose_name='실제값')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발생 시간')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 시간')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결 시간')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.sensor', verbose_name='센서')),
            ],
            options={
                'verbose_name': '알람',
                'verbose_name_plural': '알람 목록',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='측정값')),
                ('unit', models.CharField(max_length=20, verbose_name='단위')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='측정 시간')),
                ('quality', models.IntegerField(default=100, verbose_name='데이터 품질 (%)')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='monitoring.sensor', verbose_name='센서')),
            ],
            options={
                'verbose_name': '센서 데이터',
                'verbose_name_plural': '센서 데이터 목록',
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensor_data_sensor__d6a7cf_idx'), models.Index(fields=['-timestamp'], name='sensor_data_timesta_ac587d_idx')],
            },
        ),
    ]
